runtime: python39
service: default

env_variables:
  FIREBASE_STORAGE_BUCKET: "mush-scope.appspot.com"
  FIREBASE_SERVICE_ACCOUNT_PATH: "service/serviceKey.json"

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --timeout 300

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10

inbound_services:
- warmup
