runtime: python39

service_account: capstone-try-deploy@appspot.gserviceaccount.com
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

env_variables:
  FIREBASE_SERVICE_ACCOUNT_PATH: "./service/serviceKey.json"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 10

inbound_services:
- warmup
